### ISSUE TITLE
Spotify登录失败

### ISSUE THREAD

**Issue by Bryan2333** [go-musicfox/spotifox#9]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

登录Spotify时提示如下报错
![Screenshot_20231119_220721.webp](https://s2.loli.net/2023/11/19/GxmhPA2uyj1MbX3.webp)

### Environment / 运行环境

Spotifox - Using Spotify on the Command Line

Version: v1.0.2

Arch Linux with KDE Plasma 5.27.9 Wayland.

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
可以申请个spotify的client_id填到配置文件中
![image](https://github.com/go-musicfox/spotifox/assets/27605589/4d449ccf-bf32-4d1c-947c-c96ff5747d0f)

**Comment by Bryan2333** [comment]
申请的时候需要填写一个Redirect URI，这个怎么填？

**Comment by anhoder** [comment]
可以填这个 http://localhost:11999/callback

另外ha还需要在这里加上你自己的账号
![image](https://github.com/go-musicfox/spotifox/assets/27605589/25337ef4-076d-4047-9f1c-6fad4995ff64)

**Comment by Bryan2333** [comment]
登录成功，谢谢。

另外我在AUR上给Arch Linux打了个包 https://aur.archlinux.org/packages/spotifox-bin

不知能否将这个放到README中。

**Comment by anhoder** [comment]
> 登录成功，谢谢。
> 
> 另外我在AUR上给Arch Linux打了个包 https://aur.archlinux.org/packages/spotifox-bin
> 
> 不知能否将这个放到README中。

可以提个PR
